"""
demo_analemma.py

Generates (Equation-of-Time, declination) pairs for every day of 2030,
plots the analemma with matplotlib, and writes an OpenSCAD-includable
configuration file that exposes the data as a native vector.

Usage:
    python3 demo_analemma.py

Outputs:
    analemma_plot.png          – the analemma plot
    analemma_2030.scad         – OpenSCAD config; include <analemma_2030.scad>
                                 then reference ANALEMMA_DATA[day]  (0-based)
                                 where each element is [eot_minutes, declination_degrees]
"""

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from solar import annual_eot_declination

# ---------------------------------------------------------------------------
# 1.  Generate data
# ---------------------------------------------------------------------------
YEAR = 2030
pairs = annual_eot_declination(YEAR)          # list of 365 (eot_min, decl_deg)
eot   = [p[0] for p in pairs]
decl  = [p[1] for p in pairs]
days  = list(range(1, 366))                   # 1-based day-of-year

# ---------------------------------------------------------------------------
# 2.  Plot
# ---------------------------------------------------------------------------
# Month boundaries (non-leap year) and labels for the colour-coded trail
MONTH_NAMES  = ["Jan","Feb","Mar","Apr","May","Jun",
                "Jul","Aug","Sep","Oct","Nov","Dec"]
MONTH_STARTS = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]  # 1-based doy
MONTH_ENDS   = MONTH_STARTS[1:] + [366]       # exclusive

# Colour map: one colour per month, evenly spaced
cmap = plt.colormaps["tab20"].resampled(12)

fig, ax = plt.subplots(figsize=(7, 9))

# Draw each month as a separate segment so we can colour and label it
for i in range(12):
    start = MONTH_STARTS[i] - 1   # convert to 0-based index
    end   = MONTH_ENDS[i] - 1
    ax.plot(eot[start:end], decl[start:end],
            color=cmap(i), linewidth=2, solid_capstyle="round")
    # Label: place at the midpoint of the month's arc
    mid = (start + end) // 2
    ax.annotate(MONTH_NAMES[i],
                xy=(eot[mid], decl[mid]),
                fontsize=8, ha="center", va="center",
                bbox=dict(boxstyle="round,pad=0.2", facecolor="white",
                          edgecolor=cmap(i), linewidth=1.2))

# Mark Jan 1 with a small dot
ax.plot(eot[0], decl[0], "o", color=cmap(0), markersize=7, zorder=5)

# Axes labels and grid
ax.set_xlabel("Equation of Time (minutes)", fontsize=11)
ax.set_ylabel("Solar Declination (degrees)", fontsize=11)
ax.set_title(f"Analemma  {YEAR}", fontsize=14, fontweight="bold")
ax.grid(True, linestyle="--", alpha=0.5)
ax.xaxis.set_minor_locator(ticker.AutoMinorLocator(2))
ax.yaxis.set_minor_locator(ticker.AutoMinorLocator(2))
ax.grid(True, which="minor", linestyle=":", alpha=0.3)

# Horizontal and vertical zero-lines
ax.axhline(0, color="gray", linewidth=0.8, linestyle="-")
ax.axvline(0, color="gray", linewidth=0.8, linestyle="-")

fig.tight_layout()
fig.savefig("analemma_plot.png", dpi=150)
print("Saved analemma_plot.png")
plt.show()

# ---------------------------------------------------------------------------
# 3.  Write OpenSCAD config file
# ---------------------------------------------------------------------------
# The file defines a single OpenSCAD vector ANALEMMA_DATA.
# Values are rounded to 4 decimal places (sub-0.001-min / sub-0.001-deg).

SCAD_FILE = "analemma_2030.scad"

with open(SCAD_FILE, "w") as f:
    f.write(f"// analemma_2030.scad  –  auto-generated by demo_analemma.py\n")
    f.write(f"// Year: {YEAR}\n")
    f.write(f"// 365 entries, index 0 = Jan 1.  Each entry: [eot_minutes, declination_degrees]\n")
    f.write(f"// Usage in OpenSCAD:\n")
    f.write(f"//   include <analemma_2030.scad>\n")
    f.write(f"//   eot  = ANALEMMA_DATA[day_index][0];\n")
    f.write(f"//   decl = ANALEMMA_DATA[day_index][1];\n\n")

    f.write("ANALEMMA_DATA = [\n")
    for i, (e, d) in enumerate(pairs):
        comma = "," if i < 364 else " "
        f.write(f"    [{e:+.4f}, {d:+.4f}]{comma}  // day {i+1:>3}\n")
    f.write("];\n")

print(f"Saved {SCAD_FILE}")
